
CREATE OR REPLACE VIEW bronze.C_VW_COB_COBRANCA_METAS AS

WITH cob_cobranca_metas AS (
	SELECT 	
		* 
	FROM 
		landing.C_COB_COBRANCA_METAS 
)

SELECT

CAST(META_ID AS INT) AS ID_META,
CAST(TIPO_META AS STRING) AS DES_META,
CAST(ANO AS INT) AS NUM_ANO,
CAST(MES AS INT) AS NUM_MES,
CAST(VLR_META AS NUMERIC) AS VLR_META,
CAST(DATA_ALTERACAO AS DATETIME) AS DAT_ALTERACAO,
CAST(TIME_STAMP AS TIMESTAMP) AS DAT_CARGA

FROM
cob_cobranca_metas