CREATE OR REPLACE VIEW bronze.C_VW_COLIGADA AS

WITH coligada AS (
	SELECT 
		* 
	FROM
		landing.`C_VW_COLIGADA` 
)

SELECT

CAST(REGIONAL_ID AS INT)                    AS ID_REGIONAL,
CAST(ACC_ID AS INT)                         AS ID_COLIGADA,
CAST(ACF_ID AS INT)                         AS ID_FILIAL,
CAST(SEGMENTO_ID AS INT)                    AS ID_SEGMENTO,
CAST(GRUPO_ID AS INT)                       AS ID_GRUPO,
CAST(CONTADOR_ID AS INT)                    AS ID_CONTADOR,
CAST(ACG_NOME AS STRING)                    AS NOM_GRUPO,
CAST(ACS_NOME AS STRING) 			        AS NOM_SEGMENTO,
CAST(ARE_NOME AS STRING) 			        AS NOM_REGIONAL,
CAST(NOMEFANTASIA AS STRING) 		        AS NOM_FANTASIA_COLIGADA,
CAST(NOME AS STRING) 				        AS NOM_COLIGADA,
CAST(ACC_DESCRICAO AS STRING) 	            AS DES_COLIGADA,
CAST(ACC_DESCRICAO_COMPACTO AS STRING)      AS DES_COLIGADA_COMAPCTO,
CAST(RATEIO_CENTRO_CUSTO AS STRING )        AS COD_RATEIO_CC,
CAST(RATEIO_PESO AS INT) 				    AS QTD_RATEIO_PESO,
CAST(ACC_FIN_PRESTA_CONTA AS INT) 		    AS IND_FIN_PRESTA_CONTA,
CAST(FIN_PARTICIPA_RATEIO AS INT) 		    AS IND_FIN_PARTICIPA_RATEIO,
CAST(ATIVO AS INT) 						    AS IND_ATIVO,
CAST(ACC_ATIVO AS INT) 					    AS IND_COLIGADA_ATIVA,
CAST(EXTERN_PF AS INT) 					    AS IND_EXTERN_PF,
CAST(SEGMENTO_ATIVO AS INT)                 AS IND_SEGMENTO_ATIVO,
CAST(TIME_STAMP AS TIMESTAMP)               AS DAT_CARGA

FROM 
coligada

