
CREATE OR REPLACE VIEW bronze.C_VW_COB_DETALHE_STATUS AS

WITH cob_detalhe_status AS (
	SELECT 	
		* 
	FROM 
		landing.C_VW_COB_DETALHE_STATUS
)

SELECT

CAST(ID_STATUS AS INT)            AS ID_STATUS,
DESCRICAO                         AS DES_STATUS,
CAST(DATA_ALTERACAO AS DATETIME) AS DAT_ALTERCAO,
CAST(TIME_STAMP AS TIMESTAMP)     AS DAT_CARGA

FROM 
	cob_detalhe_status
