
CREATE OR REPLACE VIEW bronze.T_VW_COB_COBRANCA_CAB AS

WITH cob_cobranca_cab AS (
	SELECT 	
		* 
	FROM 
		landing.T_VW_COB_COBRANCA_CAB
)

SELECT
CAST(ID AS INT) AS ID_COB_CAB,
CODCFO AS ID_CFO,
CAST(DATA_CARGA AS DATETIME) AS DAT_ALTERACAO,
CAST(TIME_STAMP AS TIMESTAMP)     AS DAT_CARGA

FROM 
cob_cobranca_cab