
CREATE OR REPLACE VIEW bronze.T_VW_FLAN AS

WITH flan AS (
	SELECT 	
		* 
	FROM 
		landing.T_VW_FLAN
)

SELECT

CAST(IDLAN AS INT) AS ID_LAN,
CAST(CODCOLIGADA AS INT) AS ID_COLIGADA,
CAST(CODFILIAL AS INT) AS ID_FILIAL,
CAST(IDBORDERO AS INT) AS ID_BORDERO,
CODCFO AS ID_CFO,
CAST(CODCOLCFO AS INT) AS ID_COLIGADA_CFO,
CODCXA  AS ID_CAIXA,
CODCOLCXA AS ID_COLIGADA_CAIXA,
CAST(IDPGTO AS INT) AS ID_PGTO,
CAST(CODCOLPGTO AS INT) AS ID_COLIGADA_PGTO,
CAST(IDMOV AS INT) AS ID_MOV,
CODCCUSTO AS COD_CENTRO_CUSTO,
CODTDO AS COD_TDO,
CODAPLICACAO AS COD_APLICACAO,
CNABSTATUS AS COD_CNABSTATUS,
NUMERODOCUMENTO AS NUM_DOCUMENTO,
NUMBLOQUEIOS AS NUM_BLOQUEIOS,
PAGREC AS IND_PAGREC,
STATUSLAN AS IND_STATUSLAN,
HISTORICO AS DES_HISTORICO,
CAST(VALORORIGINAL AS NUMERIC) AS VLR_ORIGINAL,
CAST(VALORBAIXADO AS NUMERIC) AS VLR_BAIXA,
CAST(VALORAUXILIAR AS NUMERIC) AS VLR_AUXILIAR,
CAST(DATA_CARGA AS DATETIME) AS DAT_ALTERACAO,
CAST(DATAPAG AS DATETIME) AS DAT_PAGAMENTO,
CAST(DATABAIXA AS DATETIME) AS DAT_BAIXA,
CAST(DATACRIACAO AS DATETIME) AS DAT_CRIACAO,
CAST(DATAEMISSAO AS DATETIME) AS DAT_EMISSAO,
CAST(DATAVENCIMENTO AS DATETIME) AS DAT_VENCIMENTO,
CAST(TIME_STAMP AS TIMESTAMP)     AS DAT_CARGA

FROM 
flan