
CREATE OR REPLACE VIEW bronze.T_VW_FLANINTEGRACAO AS

WITH flanintegracao AS (
	SELECT 	
		* 
	FROM 
		landing.T_VW_FLANINTEGRACAO
)

SELECT

CAST(IDLAN AS INT) AS ID_LAN,
CAST(CODCOLIGADA AS INT) AS ID_COLIGADA,
CAST(IDCAMPO AS INT) AS ID_CAMPO,
CAST(VALOR AS NUMERIC) AS VLR_INTEGRACAO,
CAST(DATA_CARGA AS DATETIME) AS DAT_ALTERACAO,
CAST(TIME_STAMP AS TIMESTAMP)     AS DAT_CARGA

FROM 
flanintegracao